const KEY='bookstock_v1';let db=JSON.parse(localStorage.getItem(KEY)||'{"books":[],"movements":[]}');let view='dashboard',selected=null,qrScanner=null,receivePhoto=null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));const total=b=>Object.values(b.locations||{}).reduce((a,n)=>a+Number(n),0);const allQty=()=>db.books.reduce((a,b)=>a+total(b),0);const locate=b=>Object.entries(b.locations||{}).filter(([,n])=>n>0).map(([k,n])=>`${esc(k)}: ${n}`).join(' · ')||'No stock';
const tabs=[['dashboard','Dashboard'],['receive','Receive Books'],['inventory','Inventory'],['pick','Pick Books'],['history','History'],['settings','Backup']];
function go(v){stopScan();view=v;render()}function render(){ $('nav').innerHTML=tabs.map(([k,n])=>`<button class="${view===k?'active':''}" data-tab="${k}">${n}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>go(x.dataset.tab));const app=$('app');if(view==='dashboard')app.innerHTML=`<h2>Dashboard</h2><div class="stats"><div class="panel"><div class="muted">Unique titles</div><div class="stat">${db.books.length}</div></div><div class="panel"><div class="muted">Total copies</div><div class="stat">${allQty()}</div></div><div class="panel"><div class="muted">Locations in use</div><div class="stat">${new Set(db.books.flatMap(b=>Object.keys(b.locations||{}).filter(k=>b.locations[k]>0))).size}</div></div></div><div class="panel"><h3>Quick actions</h3><button class="primary" id="quickReceive">Receive a book</button> <button id="quickPick">Pick a book</button></div>`;
if(view==='receive')app.innerHTML=`<h2>Receive Books</h2><div class="panel"><label>1. Photograph front cover</label><input id="photo" type="file" accept="image/*" capture="environment"><div id="ocrStatus" class="muted">OCR supports Bulgarian Cyrillic. Review the result before saving.</div><img id="photoPreview" class="preview hidden" alt="Cover preview"><label>2. Book title *</label><input id="title" placeholder="Заглавие на книгата"><label>Author</label><input id="author" placeholder="Автор"><label>Number of copies *</label><input id="qty" type="number" min="1" step="1" value="1"><label>3. Storage location *</label><div class="row"><input id="location" placeholder="e.g. 1A" autocapitalize="characters"><button id="scanReceive">Scan QR</button></div><div id="qr-reader"></div><p class="muted">Scan the label on the bin where you are placing these copies. You can always enter its code manually.</p><button class="primary" id="receiveSave">Confirm & receive stock</button><div id="receiveMsg"></div></div>`;
if(view==='inventory')app.innerHTML=`<h2>Inventory</h2><div class="panel"><input id="search" placeholder="Search by title or author…"><div id="results"></div></div>`;
if(view==='pick')app.innerHTML=`<h2>Pick Books</h2><div class="panel"><input id="search" placeholder="Search book to pick…"><div id="results"></div></div>`;
if(view==='history')app.innerHTML=`<h2>Stock history</h2><div class="panel">${db.movements.length?db.movements.slice().reverse().map(m=>`<div class="book"><b>${esc(m.type)}</b> · ${esc(m.title)}<div class="muted">${esc(m.location)} · ${m.qty} copies · ${new Date(m.at).toLocaleString()}</div></div>`).join(''):'No movements yet.'}</div>`;
if(view==='settings')app.innerHTML=`<h2>Backup & restore</h2><div class="panel"><p>Export your inventory as a JSON backup. Restoring replaces all inventory data in this browser.</p><button id="export">Download backup</button><label>Restore a backup</label><input type="file" id="import" accept="application/json,.json"><p class="alert"><b>Important:</b> This starter stores data locally in each browser. iPhone and computer do not synchronise yet. Cloud database setup is required before relying on it across devices.</p></div>`;
wire()}
function wire(){if($('quickReceive'))$('quickReceive').onclick=()=>go('receive');if($('quickPick'))$('quickPick').onclick=()=>go('pick');if($('photo'))$('photo').onchange=ocrPhoto;if($('scanReceive'))$('scanReceive').onclick=()=>scanQR(v=>{$('location').value=v});if($('receiveSave'))$('receiveSave').onclick=receive;if($('search')){$('search').oninput=results;results()}if($('export'))$('export').onclick=exportDB;if($('import'))$('import').onchange=importDB}
async function ocrPhoto(e){const file=e.target.files[0];if(!file)return;receivePhoto=file;$('photoPreview').src=URL.createObjectURL(file);$('photoPreview').classList.remove('hidden');$('ocrStatus').textContent='Reading Bulgarian cover text… this may take a moment.';try{const result=await Tesseract.recognize(file,'bul+eng');const lines=result.data.text.split('\n').map(x=>x.trim()).filter(x=>x.length>2);if(lines.length){$('title').value=lines[0];if(lines.length>1)$('author').value=lines[1];$('ocrStatus').textContent='Text suggested from cover. Please correct title and author if needed.'}else $('ocrStatus').textContent='No readable text found. Enter details manually or try another photo.'}catch(err){$('ocrStatus').textContent='OCR unavailable. Enter title and author manually. '+err.message}}
async function scanQR(onFound){stopScan();if(!window.Html5Qrcode){alert('QR scanner could not load. Enter the bin code manually.');return}const div=$('qr-reader');if(!div)return;div.innerHTML='';try{qrScanner=new Html5Qrcode('qr-reader');await qrScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:220,height:220}},text=>{onFound(text.trim());stopScan()})}catch(e){alert('Camera unavailable. Please allow camera access or type the bin code. Camera scanning requires HTTPS.')}}
async function stopScan(){if(qrScanner){const s=qrScanner;qrScanner=null;try{await s.stop()}catch{}try{s.clear()}catch{}}}
function receive(){const title=$('title').value.trim(),author=$('author').value.trim(),location=$('location').value.trim().toUpperCase(),qty=Number($('qty').value);if(!title||!location||!Number.isSafeInteger(qty)||qty<1){$('receiveMsg').innerHTML='<p class="alert">Enter a title, positive whole-number quantity and bin location.</p>';return}const norm=s=>s.trim().toLocaleLowerCase();let book=db.books.find(b=>norm(b.title)===norm(title)&&norm(b.author)===norm(author));if(!book){book={id:crypto.randomUUID(),title,author,locations:{}};db.books.push(book)}book.locations[location]=(book.locations[location]||0)+qty;db.movements.push({type:'Received',title:book.title,location,qty,at:new Date().toISOString()});save();$('receiveMsg').innerHTML=`<p class="success">Received ${qty} copies into ${esc(location)}. Total for this title: ${total(book)}.</p>`;$('qty').value=1;$('location').value='';}
function results(){const q=$('search').value.trim().toLocaleLowerCase();const books=db.books.filter(b=>(b.title+' '+b.author).toLocaleLowerCase().includes(q));$('results').innerHTML=books.length?books.map(b=>`<div class="book"><b>${esc(b.title)}</b><div class="muted">${esc(b.author||'Author not set')}</div><p><span class="pill">${total(b)} copies</span> &nbsp; ${locate(b)}</p>${view==='pick'?`<button class="primary" data-pick="${b.id}">Pick copies</button>`:`<button data-detail="${b.id}">View / move stock</button>`}</div>`).join(''):'<p class="muted">No matching books.</p>';document.querySelectorAll('[data-pick]').forEach(x=>x.onclick=()=>pickForm(x.dataset.pick));document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>detail(x.dataset.detail))}
function pickForm(id){const b=db.books.find(b=>b.id===id);if(!b)return;const locs=Object.entries(b.locations).filter(([,n])=>n>0);$('results').innerHTML=`<h3>${esc(b.title)}</h3><p>${locate(b)}</p><label>Pick from bin</label><select id="from">${locs.map(([k,n])=>`<option value="${esc(k)}">${esc(k)} (${n} available)</option>`).join('')}</select><label>Quantity to pick</label><input id="pickQty" type="number" min="1" step="1" value="1"><p><button class="primary" id="confirmPick">Confirm picked</button> <button id="cancel">Cancel</button></p><div id="msg"></div>`;$('cancel').onclick=results;$('confirmPick').onclick=()=>{const loc=$('from').value,n=Number($('pickQty').value);if(!Number.isSafeInteger(n)||n<1||n>b.locations[loc]){$('msg').innerHTML='<p class="alert">Invalid quantity or insufficient stock.</p>';return}b.locations[loc]-=n;db.movements.push({type:'Picked',title:b.title,location:loc,qty:n,at:new Date().toISOString()});save();$('msg').innerHTML='<p class="success">Pick recorded.</p>';$('confirmPick').disabled=true}}
function detail(id){const b=db.books.find(b=>b.id===id);$('results').innerHTML=`<h3>${esc(b.title)}</h3><p>${esc(b.author)} · ${total(b)} copies</p><p>${locate(b)}</p><h3>Move copies between bins</h3><label>From</label><select id="from">${Object.entries(b.locations).filter(([,n])=>n>0).map(([k,n])=>`<option value="${esc(k)}">${esc(k)} (${n})</option>`).join('')}</select><label>To bin</label><div class="row"><input id="to" placeholder="Scan or type bin code"><button id="scanTo">Scan QR</button></div><div id="qr-reader"></div><label>Quantity</label><input id="moveQty" type="number" min="1" value="1"><p><button class="primary" id="move">Move stock</button> <button id="cancel">Back</button></p><div id="msg"></div>`;$('cancel').onclick=results;$('scanTo').onclick=()=>scanQR(v=>$('to').value=v);$('move').onclick=()=>{const from=$('from').value,to=$('to').value.trim().toUpperCase(),n=Number($('moveQty').value);if(!to||to===from||!Number.isSafeInteger(n)||n<1||n>b.locations[from]){$('msg').innerHTML='<p class="alert">Check destination and available quantity.</p>';return}b.locations[from]-=n;b.locations[to]=(b.locations[to]||0)+n;db.movements.push({type:'Moved',title:b.title,location:from+' → '+to,qty:n,at:new Date().toISOString()});save();detail(id)}}
function exportDB(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bookstock-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
async function importDB(e){const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.books)||!Array.isArray(data.movements))throw Error('Invalid backup');if(confirm('Replace ALL inventory in this browser with the backup?')){db=data;save();render()}}catch(err){alert('Could not import backup: '+err.message)}}
render();
